import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, HeartPulse, MapPin, ShieldCheck } from "lucide-react";
import { getCatTimeline } from "@/lib/data";
import { getCat } from "@/lib/server-data";
import { CatPhoto } from "@/components/CatPhoto";
import { Timeline } from "@/components/Timeline";

export const dynamic = "force-dynamic";
export default async function CatPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const cat=await getCat(slug); if(!cat)notFound(); const items=getCatTimeline(slug);
  return <div><section className="mx-auto max-w-6xl px-4 pt-6 sm:px-6 sm:pt-10"><Link href="/cats" className="btn-ghost -ml-3"><ArrowLeft size={17}/>返回图鉴</Link><div className="mt-3 grid overflow-hidden rounded-[2rem] bg-ink text-cream lg:grid-cols-[1.08fr_.92fr]"><div className="relative min-h-[380px] lg:min-h-[560px]"><CatPhoto src={cat.image} alt={`${cat.name}的档案照片`} position={cat.imagePosition} priority/></div><div className="flex flex-col justify-center p-7 sm:p-12"><div className="flex items-center gap-2"><span className={cat.status==="pending"?"rounded-full bg-amber-200 px-3 py-1 text-xs font-medium text-amber-950":"rounded-full bg-cream/15 px-3 py-1 text-xs"}>{cat.status==="pending"?"档案待更新":cat.status==="adopted"?"已被领养":"2023 正式档案"}</span><span className="rounded-full bg-cream/15 px-3 py-1 text-xs">{cat.sex}</span></div><h1 className="mt-5 text-5xl font-semibold tracking-tight">{cat.name}</h1>{cat.aliases.length>0&&<p className="mt-2 text-sm text-cream/55">也叫 {cat.aliases.join("、")}</p>}<p className="mt-6 text-base leading-7 text-cream/75">{cat.intro}</p><div className="mt-8 grid grid-cols-2 gap-5 border-t border-cream/15 pt-7 text-sm"><div><p className="text-xs text-cream/45">花色</p><p className="mt-1">{cat.coat}</p></div><div><p className="text-xs text-cream/45">收录时间</p><p className="mt-1">{cat.age}</p></div><div><p className="text-xs text-cream/45">健康状态</p><p className="mt-1">{cat.health}</p></div><div><p className="text-xs text-cream/45">绝育状态</p><p className="mt-1">{cat.neutered===true?"已绝育":cat.neutered===false?"未绝育":"待确认"}</p></div></div></div></div></section>
    <section className="mx-auto grid max-w-6xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[.72fr_1.28fr]"><aside className="space-y-4"><div className="card"><p className="eyebrow">辨认要点</p><p className="mt-3 text-sm leading-6 text-ink/65">{cat.feature}</p></div><div className="card"><p className="eyebrow">常见区域</p><p className="mt-3 flex items-center gap-2 font-medium"><MapPin size={17} className="text-moss"/>{cat.area}</p><p className="mt-2 text-xs leading-5 text-ink/45">为保护猫咪，本站不展示精确坐标和藏身点。</p></div><div className="card"><p className="eyebrow">相处提示</p><p className="mt-3 text-sm leading-6 text-ink/65">{cat.temperament}</p><p className="mt-3 flex items-center gap-2 text-xs text-moss"><ShieldCheck size={15}/>请勿追逐、围堵或强行投喂</p></div><Link href={`/upload?cat=${cat.id}`} className="btn-primary w-full justify-center">记录一次遇见</Link></aside><div><div className="mb-5 flex items-center justify-between"><div><p className="eyebrow">TIMELINE</p><h2 className="mt-1 text-2xl font-semibold">{cat.name}的时间线</h2></div><span className="text-sm text-ink/45">{cat.sightings} 条记录</span></div>{items.length?<Timeline items={items}/>:<div className="card py-14 text-center"><HeartPulse className="mx-auto text-moss"/><p className="mt-3 font-medium">还没有公开动态</p><p className="mt-1 text-sm text-ink/50">你可以成为第一位记录者。</p></div>}</div></section></div>
}
