# Generated by Django 5.2.6 on 2026-08-15 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='征集标题')),
                ('summary', models.TextField(verbose_name='说明')),
                ('starts_at', models.DateTimeField(verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(verbose_name='截止时间')),
                ('is_published', models.BooleanField(default=False, verbose_name='公开展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '征集活动',
                'verbose_name_plural': '征集活动',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='名字')),
                ('slug', models.SlugField(unique=True, verbose_name='网址标识')),
                ('aliases', models.CharField(blank=True, help_text='多个别名用顿号分隔', max_length=120, verbose_name='别名')),
                ('sex', models.CharField(choices=[('公猫', '公猫'), ('母猫', '母猫'), ('未知', '未知')], default='未知', max_length=8, verbose_name='性别')),
                ('estimated_age', models.CharField(blank=True, max_length=60, verbose_name='年龄/收录时间')),
                ('coat', models.CharField(max_length=100, verbose_name='花色')),
                ('distinctive_features', models.TextField(verbose_name='辨认特征')),
                ('area_public', models.CharField(default='校园内', max_length=120, verbose_name='公开活动区域')),
                ('temperament', models.CharField(blank=True, max_length=160, verbose_name='性格')),
                ('health_status', models.CharField(blank=True, max_length=160, verbose_name='健康状态')),
                ('neutered', models.BooleanField(blank=True, null=True, verbose_name='已绝育')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('photo', models.ImageField(blank=True, upload_to='cat/photos/%Y/%m/', verbose_name='档案照片')),
                ('status', models.CharField(choices=[('official', '正式档案'), ('pending', '待确认'), ('adopted', '已领养'), ('missing', '待寻找'), ('memorial', '纪念')], default='official', max_length=20, verbose_name='档案状态')),
                ('source_year', models.PositiveSmallIntegerField(default=2023, verbose_name='来源年份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '猫咪档案',
                'verbose_name_plural': '猫咪档案',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(max_length=40, verbose_name='暂定名字')),
                ('coat', models.CharField(max_length=100, verbose_name='花色')),
                ('distinctive_features', models.TextField(verbose_name='辨认特征')),
                ('area_public', models.CharField(max_length=120, verbose_name='公开区域')),
                ('notes', models.TextField(blank=True, verbose_name='其他线索')),
                ('photo', models.ImageField(blank=True, upload_to='cat/applications/%Y/%m/', verbose_name='照片')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='联系方式（不公开）')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('approved', '已通过'), ('merged', '已合并'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '新猫建档申请',
                'verbose_name_plural': '新猫建档申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='投稿标题')),
                ('body', models.TextField(verbose_name='投稿内容')),
                ('image', models.ImageField(blank=True, upload_to='cat/campaigns/%Y/%m/', verbose_name='投稿图片')),
                ('contact_private', models.CharField(max_length=120, verbose_name='联系方式（不公开）')),
                ('consent_granted', models.BooleanField(default=False, verbose_name='已授权展示')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已采用'), ('rejected', '未采用')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='registry.campaign', verbose_name='征集活动')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.cat', verbose_name='关联猫咪')),
            ],
            options={
                'verbose_name': '征集投稿',
                'verbose_name_plural': '征集投稿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sighting', '目击'), ('update', '近况'), ('story', '故事'), ('health', '健康')], default='sighting', max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('occurred_at', models.DateField(verbose_name='发生日期')),
                ('area_public', models.CharField(max_length=120, verbose_name='公开区域')),
                ('image', models.ImageField(blank=True, upload_to='cat/timeline/%Y/%m/', verbose_name='照片')),
                ('author_name', models.CharField(blank=True, max_length=60, verbose_name='记录者')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱（不公开）')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精选故事')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='已下架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline', to='registry.cat', verbose_name='猫咪')),
            ],
            options={
                'verbose_name': '时间线记录',
                'verbose_name_plural': '时间线记录',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120, verbose_name='原因')),
                ('detail', models.TextField(blank=True, verbose_name='说明')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='联系方式（不公开）')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('dismissed', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.timelineentry', verbose_name='被举报内容')),
            ],
            options={
                'verbose_name': '内容举报',
                'verbose_name_plural': '内容举报',
                'ordering': ['-created_at'],
            },
        ),
    ]
